// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agwvasaxbggegqblxgej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnd3Zhc2F4YmdnZWdxYmx4Z2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDg4MzIsImV4cCI6MjA2MzM4NDgzMn0.omMVEEYK0fjafliWYAIzpcsz33jM3Kp6_lWP84XUlhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);